// 由 scripts/generate-manifest.ts 在 build 时自动生成，请勿手动编辑。

export const commandToGroup: Record<string, string> = {
  "initZentao": "init",
  "activateTask": "task",
  "assignTask": "task",
  "batchActivateTasks": "task",
  "batchAssignTasksTo": "task",
  "batchCancelTasks": "task",
  "batchChangeTaskBranch": "task",
  "batchChangeTaskModule": "task",
  "batchChangeTaskPlan": "task",
  "batchCloseTasks": "task",
  "batchFinishTasks": "task",
  "cancelTask": "task",
  "closeTask": "task",
  "confirmTaskStoryChange": "task",
  "deleteTask": "task",
  "deleteTaskEstimate": "task",
  "editTaskEstimate": "task",
  "finishTask": "task",
  "getMyTasks": "task",
  "getTaskDetail": "task",
  "pauseTask": "task",
  "recordTaskEstimate": "task",
  "restartTask": "task",
  "startTask": "task",
  "updateTask": "task",
  "activateTodo": "todo",
  "assignTodo": "todo",
  "batchCloseTodos": "todo",
  "batchFinishTodos": "todo",
  "closeTodo": "todo",
  "createTodo": "todo",
  "deleteTodo": "todo",
  "finishTodo": "todo",
  "getMyTodos": "todo",
  "getTodoDetail": "todo",
  "importTodosToToday": "todo",
  "startTodo": "todo",
  "updateTodo": "todo",
  "activateBug": "bug",
  "assignBug": "bug",
  "batchActivateBugs": "bug",
  "batchAssignBugs": "bug",
  "batchChangeBugBranch": "bug",
  "batchChangeBugModule": "bug",
  "batchChangeBugPlan": "bug",
  "batchCloseBugs": "bug",
  "batchConfirmBugs": "bug",
  "batchResolveBugs": "bug",
  "closeBug": "bug",
  "confirmBug": "bug",
  "confirmBugStoryChange": "bug",
  "createBug": "bug",
  "deleteBug": "bug",
  "getBugDetail": "bug",
  "getMyBugs": "bug",
  "getProductBugs": "bug",
  "okBug": "bug",
  "resolveBug": "bug",
  "updateBug": "bug",
  "getProductStories": "story",
  "getStoryDetail": "story",
  "computeExecutionBurn": "execution",
  "confirmExecutionStoryChange": "execution",
  "getExecutionBugs": "execution",
  "getExecutionBuilds": "execution",
  "getExecutionDailyBugStats": "execution",
  "getExecutionDetail": "execution",
  "getExecutionDynamic": "execution",
  "getProjectExecutions": "execution",
  "addComment": "comment",
  "getComments": "comment",
  "getMyProfile": "profile",
  "who-am-i": "profile",
  "whoami": "profile",
  "getMyBugStatistics": "statistics",
  "getMyTaskStatistics": "statistics",
  "getMyWeeklyActivity": "statistics",
  "getBugRelatedStory": "relation",
  "getStoryRelatedBugs": "relation",
  "getDevelopmentContext": "context",
  "getProductDetail": "product",
  "getProducts": "product",
  "getProjectDetail": "project",
  "getProjects": "project",
  "getProductTestCases": "testcase",
  "getTestCaseDetail": "testcase",
  "getTestTaskDetail": "testtask",
  "getTestTasks": "testtask",
  "getProgramDetail": "program",
  "getPrograms": "program",
  "activatePlan": "plan",
  "closePlan": "plan",
  "finishPlan": "plan",
  "getPlanDetail": "plan",
  "getProductPlans": "plan",
  "startPlan": "plan",
  "assignBuildTo": "build",
  "getBuildDetail": "build",
  "getProjectBuilds": "build",
  "notifyBuildBug": "build",
  "getProjectReleases": "release",
  "getReleaseDetail": "release",
  "analyzeBugResources": "resource-analysis",
  "analyzeTaskResources": "resource-analysis",
  "searchStories": "search",
  "searchStoriesByProductName": "search",
  "activateStory": "story-write",
  "assignStory": "story-write",
  "batchAssignStoriesTo": "story-write",
  "batchChangeStoryBranch": "story-write",
  "batchChangeStoryModule": "story-write",
  "batchChangeStoryPlan": "story-write",
  "batchChangeStoryStage": "story-write",
  "batchCloseStories": "story-write",
  "batchReviewStories": "story-write",
  "changeStory": "story-write",
  "closeStory": "story-write",
  "createStory": "story-write",
  "linkStoriesToStory": "story-write",
  "processStoryChange": "story-write",
  "recallStory": "story-write",
  "reviewStory": "story-write",
  "submitStoryReview": "story-write",
  "unlinkStoryFromStory": "story-write",
  "updateStory": "story-write",
  "createTaskFromBug": "task-derived",
  "createTaskFromStory": "task-derived",
  "linkBugsToPlan": "plan-relation",
  "linkStoriesToPlan": "plan-relation",
  "unlinkBugsFromPlan": "plan-relation",
  "unlinkStoriesFromPlan": "plan-relation",
  "activateExecution": "execution-write",
  "closeExecution": "execution-write",
  "putoffExecution": "execution-write",
  "startExecution": "execution-write",
  "suspendExecution": "execution-write",
  "updateExecution": "execution-write",
  "batchUnlinkBugsFromBuild": "build-write",
  "batchUnlinkStoriesFromBuild": "build-write",
  "createBuild": "build-write",
  "linkBugsToBuild": "build-write",
  "linkStoriesToBuild": "build-write",
  "unlinkBugFromBuild": "build-write",
  "unlinkStoryFromBuild": "build-write",
  "updateBuild": "build-write",
  "batchUnlinkBugsFromRelease": "release-write",
  "batchUnlinkStoriesFromRelease": "release-write",
  "changeReleaseStatus": "release-write",
  "deleteRelease": "release-write",
  "linkBugsToRelease": "release-write",
  "linkStoriesToRelease": "release-write",
  "notifyRelease": "release-write",
  "unlinkBugFromRelease": "release-write",
  "unlinkStoryFromRelease": "release-write",
  "batchConfirmTestCaseStoryChange": "testcase-write",
  "confirmTestCaseLibcaseChange": "testcase-write",
  "confirmTestCaseStoryChange": "testcase-write",
  "createTestCase": "testcase-write",
  "ignoreTestCaseLibcaseChange": "testcase-write",
  "updateTestCase": "testcase-write",
  "activateTestTask": "testtask-write",
  "blockTestTask": "testtask-write",
  "closeTestTask": "testtask-write",
  "createTestTask": "testtask-write",
  "deleteTestTask": "testtask-write",
  "startTestTask": "testtask-write",
  "updateTestTask": "testtask-write"
};

export const groupCommands: Record<string, string[]> = {
  "init": [
    "initZentao"
  ],
  "task": [
    "activateTask",
    "assignTask",
    "batchActivateTasks",
    "batchAssignTasksTo",
    "batchCancelTasks",
    "batchChangeTaskBranch",
    "batchChangeTaskModule",
    "batchChangeTaskPlan",
    "batchCloseTasks",
    "batchFinishTasks",
    "cancelTask",
    "closeTask",
    "confirmTaskStoryChange",
    "deleteTask",
    "deleteTaskEstimate",
    "editTaskEstimate",
    "finishTask",
    "getMyTasks",
    "getTaskDetail",
    "pauseTask",
    "recordTaskEstimate",
    "restartTask",
    "startTask",
    "updateTask"
  ],
  "todo": [
    "activateTodo",
    "assignTodo",
    "batchCloseTodos",
    "batchFinishTodos",
    "closeTodo",
    "createTodo",
    "deleteTodo",
    "finishTodo",
    "getMyTodos",
    "getTodoDetail",
    "importTodosToToday",
    "startTodo",
    "updateTodo"
  ],
  "bug": [
    "activateBug",
    "assignBug",
    "batchActivateBugs",
    "batchAssignBugs",
    "batchChangeBugBranch",
    "batchChangeBugModule",
    "batchChangeBugPlan",
    "batchCloseBugs",
    "batchConfirmBugs",
    "batchResolveBugs",
    "closeBug",
    "confirmBug",
    "confirmBugStoryChange",
    "createBug",
    "deleteBug",
    "getBugDetail",
    "getMyBugs",
    "getProductBugs",
    "okBug",
    "resolveBug",
    "updateBug"
  ],
  "story": [
    "getProductStories",
    "getStoryDetail"
  ],
  "execution": [
    "computeExecutionBurn",
    "confirmExecutionStoryChange",
    "getExecutionBugs",
    "getExecutionBuilds",
    "getExecutionDailyBugStats",
    "getExecutionDetail",
    "getExecutionDynamic",
    "getProjectExecutions"
  ],
  "comment": [
    "addComment",
    "getComments"
  ],
  "profile": [
    "getMyProfile",
    "who-am-i",
    "whoami"
  ],
  "statistics": [
    "getMyBugStatistics",
    "getMyTaskStatistics",
    "getMyWeeklyActivity"
  ],
  "relation": [
    "getBugRelatedStory",
    "getStoryRelatedBugs"
  ],
  "context": [
    "getDevelopmentContext"
  ],
  "product": [
    "getProductDetail",
    "getProducts"
  ],
  "project": [
    "getProjectDetail",
    "getProjects"
  ],
  "testcase": [
    "getProductTestCases",
    "getTestCaseDetail"
  ],
  "testtask": [
    "getTestTaskDetail",
    "getTestTasks"
  ],
  "program": [
    "getProgramDetail",
    "getPrograms"
  ],
  "plan": [
    "activatePlan",
    "closePlan",
    "finishPlan",
    "getPlanDetail",
    "getProductPlans",
    "startPlan"
  ],
  "build": [
    "assignBuildTo",
    "getBuildDetail",
    "getProjectBuilds",
    "notifyBuildBug"
  ],
  "release": [
    "getProjectReleases",
    "getReleaseDetail"
  ],
  "resource-analysis": [
    "analyzeBugResources",
    "analyzeTaskResources"
  ],
  "search": [
    "searchStories",
    "searchStoriesByProductName"
  ],
  "story-write": [
    "activateStory",
    "assignStory",
    "batchAssignStoriesTo",
    "batchChangeStoryBranch",
    "batchChangeStoryModule",
    "batchChangeStoryPlan",
    "batchChangeStoryStage",
    "batchCloseStories",
    "batchReviewStories",
    "changeStory",
    "closeStory",
    "createStory",
    "linkStoriesToStory",
    "processStoryChange",
    "recallStory",
    "reviewStory",
    "submitStoryReview",
    "unlinkStoryFromStory",
    "updateStory"
  ],
  "task-derived": [
    "createTaskFromBug",
    "createTaskFromStory"
  ],
  "plan-write": [],
  "plan-relation": [
    "linkBugsToPlan",
    "linkStoriesToPlan",
    "unlinkBugsFromPlan",
    "unlinkStoriesFromPlan"
  ],
  "execution-write": [
    "activateExecution",
    "closeExecution",
    "putoffExecution",
    "startExecution",
    "suspendExecution",
    "updateExecution"
  ],
  "build-write": [
    "batchUnlinkBugsFromBuild",
    "batchUnlinkStoriesFromBuild",
    "createBuild",
    "linkBugsToBuild",
    "linkStoriesToBuild",
    "unlinkBugFromBuild",
    "unlinkStoryFromBuild",
    "updateBuild"
  ],
  "release-write": [
    "batchUnlinkBugsFromRelease",
    "batchUnlinkStoriesFromRelease",
    "changeReleaseStatus",
    "deleteRelease",
    "linkBugsToRelease",
    "linkStoriesToRelease",
    "notifyRelease",
    "unlinkBugFromRelease",
    "unlinkStoryFromRelease"
  ],
  "testcase-write": [
    "batchConfirmTestCaseStoryChange",
    "confirmTestCaseLibcaseChange",
    "confirmTestCaseStoryChange",
    "createTestCase",
    "ignoreTestCaseLibcaseChange",
    "updateTestCase"
  ],
  "testtask-write": [
    "activateTestTask",
    "blockTestTask",
    "closeTestTask",
    "createTestTask",
    "deleteTestTask",
    "startTestTask",
    "updateTestTask"
  ]
};
