// 由 scripts/generate-manifest.ts 在 build 时自动生成，请勿手动编辑。

export const commandToGroup: Record<string, string> = {
  "initZentao": "init",
  "activateTask": "task",
  "assignTask": "task",
  "batchActivateTasks": "task",
  "batchAssignTasksTo": "task",
  "batchCancelTasks": "task",
  "batchChangeTaskBranch": "task",
  "batchChangeTaskModule": "task",
  "batchChangeTaskPlan": "task",
  "batchChangeTaskStory": "task",
  "batchCloseTasks": "task",
  "batchCreateTasks": "task",
  "batchEditTasks": "task",
  "batchFinishTasks": "task",
  "cancelTask": "task",
  "closeTask": "task",
  "confirmTaskStoryChange": "task",
  "deleteTask": "task",
  "deleteTaskEstimate": "task",
  "editTaskEstimate": "task",
  "editTaskTeam": "task",
  "exportTasks": "task",
  "finishTask": "task",
  "getMyTasks": "task",
  "getTaskDetail": "task",
  "importTaskToLib": "task",
  "pauseTask": "task",
  "recordTaskEstimate": "task",
  "restartTask": "task",
  "startTask": "task",
  "updateTask": "task",
  "activateTodo": "todo",
  "assignTodo": "todo",
  "batchCloseTodos": "todo",
  "batchCreateTodos": "todo",
  "batchEditTodos": "todo",
  "batchFinishTodos": "todo",
  "closeTodo": "todo",
  "createTodo": "todo",
  "createTodoCycle": "todo",
  "deleteTodo": "todo",
  "exportTodos": "todo",
  "finishTodo": "todo",
  "getMyTodos": "todo",
  "getTodoDetail": "todo",
  "importTodosToToday": "todo",
  "startTodo": "todo",
  "updateTodo": "todo",
  "activateBug": "bug",
  "assignBug": "bug",
  "batchActivateBugs": "bug",
  "batchAssignBugs": "bug",
  "batchChangeBugBranch": "bug",
  "batchChangeBugModule": "bug",
  "batchChangeBugPlan": "bug",
  "batchCloseBugs": "bug",
  "batchConfirmBugs": "bug",
  "batchCreateBugs": "bug",
  "batchEditBugs": "bug",
  "batchResolveBugs": "bug",
  "closeBug": "bug",
  "confirmBug": "bug",
  "confirmBugStoryChange": "bug",
  "createBug": "bug",
  "deleteBug": "bug",
  "deleteBugViaForm": "bug",
  "exportBugs": "bug",
  "getBugDetail": "bug",
  "getBugTrack": "bug",
  "getMyBugs": "bug",
  "getProductBugs": "bug",
  "linkBugs": "bug",
  "okBug": "bug",
  "resolveBug": "bug",
  "updateBug": "bug",
  "batchToTaskStories": "story",
  "getProductStories": "story",
  "getStoryDetail": "story",
  "computeExecutionBurn": "execution",
  "confirmExecutionStoryChange": "execution",
  "getExecutionAll": "execution",
  "getExecutionBugs": "execution",
  "getExecutionBuilds": "execution",
  "getExecutionDailyBugStats": "execution",
  "getExecutionDetail": "execution",
  "getExecutionDynamic": "execution",
  "getExecutionExecutionKanban": "execution",
  "getExecutionKanban": "execution",
  "getExecutionManageMembers": "execution",
  "getExecutionStoryKanban": "execution",
  "getExecutionStoryTasks": "execution",
  "getExecutionTaskKanban": "execution",
  "getExecutionTrack": "execution",
  "getProjectExecutions": "execution",
  "addComment": "comment",
  "getComments": "comment",
  "getMyProfile": "profile",
  "who-am-i": "profile",
  "whoami": "profile",
  "getMyBugStatistics": "statistics",
  "getMyTaskStatistics": "statistics",
  "getMyWeeklyActivity": "statistics",
  "getBugRelatedStory": "relation",
  "getStoryRelatedBugs": "relation",
  "getDevelopmentContext": "context",
  "getProductDetail": "product",
  "getProducts": "product",
  "manageProductLine": "product",
  "getProjectDetail": "project",
  "getProjects": "project",
  "getProductTestCases": "testcase",
  "getTestCaseDetail": "testcase",
  "updateTestCaseOrder": "testcase",
  "getTestTaskDetail": "testtask",
  "getTestTasks": "testtask",
  "getProgramDetail": "program",
  "getPrograms": "program",
  "activatePlan": "plan",
  "closePlan": "plan",
  "finishPlan": "plan",
  "getPlanDetail": "plan",
  "getProductPlans": "plan",
  "startPlan": "plan",
  "assignBuildTo": "build",
  "deleteBuild": "build",
  "getBuildDetail": "build",
  "getProjectBuilds": "build",
  "notifyBuildBug": "build",
  "getProjectReleases": "release",
  "getReleaseDetail": "release",
  "analyzeBugResources": "resource-analysis",
  "analyzeTaskResources": "resource-analysis",
  "searchStories": "search",
  "searchStoriesByProductName": "search",
  "activateStory": "story-write",
  "assignStory": "story-write",
  "batchAssignStoriesTo": "story-write",
  "batchChangeStoryBranch": "story-write",
  "batchChangeStoryModule": "story-write",
  "batchChangeStoryPlan": "story-write",
  "batchChangeStoryStage": "story-write",
  "batchCloseStories": "story-write",
  "batchCreateStories": "story-write",
  "batchEditStories": "story-write",
  "batchReviewStories": "story-write",
  "changeStory": "story-write",
  "closeStory": "story-write",
  "createStory": "story-write",
  "deleteStory": "story-write",
  "exportStories": "story-write",
  "linkRequirements": "story-write",
  "linkStoriesToStory": "story-write",
  "processStoryChange": "story-write",
  "recallStory": "story-write",
  "reviewStory": "story-write",
  "submitStoryReview": "story-write",
  "unlinkStoryFromStory": "story-write",
  "updateStory": "story-write",
  "createTask": "task-derived",
  "createTaskFromBug": "task-derived",
  "createTaskFromStory": "task-derived",
  "linkBugsToPlan": "plan-relation",
  "linkStoriesToPlan": "plan-relation",
  "unlinkBugsFromPlan": "plan-relation",
  "unlinkStoriesFromPlan": "plan-relation",
  "activateExecution": "execution-write",
  "addExecutionMember": "execution-write",
  "addExecutionWhitelist": "execution-write",
  "batchChangeExecutionStatus": "execution-write",
  "batchEditExecutions": "execution-write",
  "batchImportBugsToExecution": "execution-write",
  "batchUnlinkStoriesFromExecution": "execution-write",
  "closeExecution": "execution-write",
  "computeCfd": "execution-write",
  "createExecution": "execution-write",
  "deleteExecution": "execution-write",
  "fixFirstExecution": "execution-write",
  "importBugToExecution": "execution-write",
  "linkStoriesToExecution": "execution-write",
  "linkStoryToExecutionSingle": "execution-write",
  "putoffExecution": "execution-write",
  "startExecution": "execution-write",
  "storyEstimate": "execution-write",
  "storySortExecution": "execution-write",
  "suspendExecution": "execution-write",
  "unbindExecutionWhitelist": "execution-write",
  "unlinkMemberFromExecution": "execution-write",
  "unlinkStoryFromExecution": "execution-write",
  "updateExecution": "execution-write",
  "updateExecutionOrder": "execution-write",
  "batchUnlinkBugsFromBuild": "build-write",
  "batchUnlinkStoriesFromBuild": "build-write",
  "createBuild": "build-write",
  "linkBugsToBuild": "build-write",
  "linkStoriesToBuild": "build-write",
  "unlinkBugFromBuild": "build-write",
  "unlinkStoryFromBuild": "build-write",
  "updateBuild": "build-write",
  "batchUnlinkBugsFromRelease": "release-write",
  "batchUnlinkStoriesFromRelease": "release-write",
  "changeReleaseStatus": "release-write",
  "createRelease": "release-write",
  "deleteRelease": "release-write",
  "exportRelease": "release-write",
  "linkBugsToRelease": "release-write",
  "linkStoriesToRelease": "release-write",
  "notifyRelease": "release-write",
  "unlinkBugFromRelease": "release-write",
  "unlinkStoryFromRelease": "release-write",
  "updateRelease": "release-write",
  "batchAssignTestCases": "testcase-write",
  "batchChangeTestCaseBranch": "testcase-write",
  "batchChangeTestCaseModule": "testcase-write",
  "batchChangeTestCaseType": "testcase-write",
  "batchConfirmTestCaseStoryChange": "testcase-write",
  "batchCreateTestCases": "testcase-write",
  "batchDeleteTestCases": "testcase-write",
  "batchEditTestCases": "testcase-write",
  "batchReviewTestCases": "testcase-write",
  "confirmTestCaseChange": "testcase-write",
  "confirmTestCaseLibcaseChange": "testcase-write",
  "confirmTestCaseStoryChange": "testcase-write",
  "createBugFromTestCase": "testcase-write",
  "createTestCase": "testcase-write",
  "deleteTestCase": "testcase-write",
  "editTestCaseViaForm": "testcase-write",
  "exportTestCases": "testcase-write",
  "exportTestCaseTemplate": "testcase-write",
  "ignoreTestCaseLibcaseChange": "testcase-write",
  "importTestCases": "testcase-write",
  "importTestCasesFromLib": "testcase-write",
  "importTestCaseToLib": "testcase-write",
  "linkBugToTestCase": "testcase-write",
  "linkCasesToBug": "testcase-write",
  "linkCasesToTestCase": "testcase-write",
  "reviewTestCase": "testcase-write",
  "unlinkBugFromTestCase": "testcase-write",
  "updateTestCase": "testcase-write",
  "activateTestTask": "testtask-write",
  "batchAssignTestTasks": "testtask-write",
  "batchRunTestCases": "testtask-write",
  "batchUnlinkCases": "testtask-write",
  "blockTestTask": "testtask-write",
  "closeTestTask": "testtask-write",
  "createTestTask": "testtask-write",
  "deleteTestTask": "testtask-write",
  "importTestTaskUnitResult": "testtask-write",
  "linkCaseToTestTask": "testtask-write",
  "runCase": "testtask-write",
  "startTestTask": "testtask-write",
  "unlinkCase": "testtask-write",
  "updateTestTask": "testtask-write",
  "addProductWhitelist": "product-write",
  "batchEditProducts": "product-write",
  "closeProduct": "product-write",
  "createProduct": "product-write",
  "deleteProduct": "product-write",
  "editProduct": "product-write",
  "exportProducts": "product-write",
  "getProductAll": "product-write",
  "getProductDashboard": "product-write",
  "getProductDynamic": "product-write",
  "getProductRoadmap": "product-write",
  "getProductTrack": "product-write",
  "getProductWhitelist": "product-write",
  "setProductOrder": "product-write",
  "unbindProductWhitelist": "product-write",
  "activateProject": "project-write",
  "addProjectWhitelist": "project-write",
  "batchEditProjects": "project-write",
  "closeProject": "project-write",
  "copyProjectGroup": "project-write",
  "createProject": "project-write",
  "createProjectGroup": "project-write",
  "deleteProject": "project-write",
  "editProject": "project-write",
  "editProjectGroup": "project-write",
  "getProjectDynamic": "project-write",
  "getProjectGroup": "project-write",
  "getProjectLinkedProducts": "project-write",
  "getProjectManageMembers": "project-write",
  "getProjectTeam": "project-write",
  "getProjectWhitelist": "project-write",
  "setProjectOrder": "project-write",
  "startProject": "project-write",
  "suspendProject": "project-write",
  "unbindProjectWhitelist": "project-write",
  "unlinkProjectMember": "project-write",
  "activateProgram": "program-write",
  "batchUnlinkProgramStakeholders": "program-write",
  "closeProgram": "program-write",
  "createProgram": "program-write",
  "createProgramStakeholder": "program-write",
  "deleteProgram": "program-write",
  "editProgram": "program-write",
  "getProgramAll": "program-write",
  "getProgramStakeholders": "program-write",
  "getProgramTrack": "program-write",
  "setProgramOrder": "program-write",
  "startProgram": "program-write",
  "suspendProgram": "program-write",
  "unbindProgramWhitelist": "program-write",
  "unlinkProgramStakeholder": "program-write"
};

export const groupCommands: Record<string, string[]> = {
  "init": [
    "initZentao"
  ],
  "task": [
    "activateTask",
    "assignTask",
    "batchActivateTasks",
    "batchAssignTasksTo",
    "batchCancelTasks",
    "batchChangeTaskBranch",
    "batchChangeTaskModule",
    "batchChangeTaskPlan",
    "batchChangeTaskStory",
    "batchCloseTasks",
    "batchCreateTasks",
    "batchEditTasks",
    "batchFinishTasks",
    "cancelTask",
    "closeTask",
    "confirmTaskStoryChange",
    "deleteTask",
    "deleteTaskEstimate",
    "editTaskEstimate",
    "editTaskTeam",
    "exportTasks",
    "finishTask",
    "getMyTasks",
    "getTaskDetail",
    "importTaskToLib",
    "pauseTask",
    "recordTaskEstimate",
    "restartTask",
    "startTask",
    "updateTask"
  ],
  "todo": [
    "activateTodo",
    "assignTodo",
    "batchCloseTodos",
    "batchCreateTodos",
    "batchEditTodos",
    "batchFinishTodos",
    "closeTodo",
    "createTodo",
    "createTodoCycle",
    "deleteTodo",
    "exportTodos",
    "finishTodo",
    "getMyTodos",
    "getTodoDetail",
    "importTodosToToday",
    "startTodo",
    "updateTodo"
  ],
  "bug": [
    "activateBug",
    "assignBug",
    "batchActivateBugs",
    "batchAssignBugs",
    "batchChangeBugBranch",
    "batchChangeBugModule",
    "batchChangeBugPlan",
    "batchCloseBugs",
    "batchConfirmBugs",
    "batchCreateBugs",
    "batchEditBugs",
    "batchResolveBugs",
    "closeBug",
    "confirmBug",
    "confirmBugStoryChange",
    "createBug",
    "deleteBug",
    "deleteBugViaForm",
    "exportBugs",
    "getBugDetail",
    "getBugTrack",
    "getMyBugs",
    "getProductBugs",
    "linkBugs",
    "okBug",
    "resolveBug",
    "updateBug"
  ],
  "story": [
    "batchToTaskStories",
    "getProductStories",
    "getStoryDetail"
  ],
  "execution": [
    "computeExecutionBurn",
    "confirmExecutionStoryChange",
    "getExecutionAll",
    "getExecutionBugs",
    "getExecutionBuilds",
    "getExecutionDailyBugStats",
    "getExecutionDetail",
    "getExecutionDynamic",
    "getExecutionExecutionKanban",
    "getExecutionKanban",
    "getExecutionManageMembers",
    "getExecutionStoryKanban",
    "getExecutionStoryTasks",
    "getExecutionTaskKanban",
    "getExecutionTrack",
    "getProjectExecutions"
  ],
  "comment": [
    "addComment",
    "getComments"
  ],
  "profile": [
    "getMyProfile",
    "who-am-i",
    "whoami"
  ],
  "statistics": [
    "getMyBugStatistics",
    "getMyTaskStatistics",
    "getMyWeeklyActivity"
  ],
  "relation": [
    "getBugRelatedStory",
    "getStoryRelatedBugs"
  ],
  "context": [
    "getDevelopmentContext"
  ],
  "product": [
    "getProductDetail",
    "getProducts",
    "manageProductLine"
  ],
  "project": [
    "getProjectDetail",
    "getProjects"
  ],
  "testcase": [
    "getProductTestCases",
    "getTestCaseDetail",
    "updateTestCaseOrder"
  ],
  "testtask": [
    "getTestTaskDetail",
    "getTestTasks"
  ],
  "program": [
    "getProgramDetail",
    "getPrograms"
  ],
  "plan": [
    "activatePlan",
    "closePlan",
    "finishPlan",
    "getPlanDetail",
    "getProductPlans",
    "startPlan"
  ],
  "build": [
    "assignBuildTo",
    "deleteBuild",
    "getBuildDetail",
    "getProjectBuilds",
    "notifyBuildBug"
  ],
  "release": [
    "getProjectReleases",
    "getReleaseDetail"
  ],
  "resource-analysis": [
    "analyzeBugResources",
    "analyzeTaskResources"
  ],
  "search": [
    "searchStories",
    "searchStoriesByProductName"
  ],
  "story-write": [
    "activateStory",
    "assignStory",
    "batchAssignStoriesTo",
    "batchChangeStoryBranch",
    "batchChangeStoryModule",
    "batchChangeStoryPlan",
    "batchChangeStoryStage",
    "batchCloseStories",
    "batchCreateStories",
    "batchEditStories",
    "batchReviewStories",
    "changeStory",
    "closeStory",
    "createStory",
    "deleteStory",
    "exportStories",
    "linkRequirements",
    "linkStoriesToStory",
    "processStoryChange",
    "recallStory",
    "reviewStory",
    "submitStoryReview",
    "unlinkStoryFromStory",
    "updateStory"
  ],
  "task-derived": [
    "createTask",
    "createTaskFromBug",
    "createTaskFromStory"
  ],
  "plan-write": [],
  "plan-relation": [
    "linkBugsToPlan",
    "linkStoriesToPlan",
    "unlinkBugsFromPlan",
    "unlinkStoriesFromPlan"
  ],
  "execution-write": [
    "activateExecution",
    "addExecutionMember",
    "addExecutionWhitelist",
    "batchChangeExecutionStatus",
    "batchEditExecutions",
    "batchImportBugsToExecution",
    "batchUnlinkStoriesFromExecution",
    "closeExecution",
    "computeCfd",
    "createExecution",
    "deleteExecution",
    "fixFirstExecution",
    "importBugToExecution",
    "linkStoriesToExecution",
    "linkStoryToExecutionSingle",
    "putoffExecution",
    "startExecution",
    "storyEstimate",
    "storySortExecution",
    "suspendExecution",
    "unbindExecutionWhitelist",
    "unlinkMemberFromExecution",
    "unlinkStoryFromExecution",
    "updateExecution",
    "updateExecutionOrder"
  ],
  "build-write": [
    "batchUnlinkBugsFromBuild",
    "batchUnlinkStoriesFromBuild",
    "createBuild",
    "linkBugsToBuild",
    "linkStoriesToBuild",
    "unlinkBugFromBuild",
    "unlinkStoryFromBuild",
    "updateBuild"
  ],
  "release-write": [
    "batchUnlinkBugsFromRelease",
    "batchUnlinkStoriesFromRelease",
    "changeReleaseStatus",
    "createRelease",
    "deleteRelease",
    "exportRelease",
    "linkBugsToRelease",
    "linkStoriesToRelease",
    "notifyRelease",
    "unlinkBugFromRelease",
    "unlinkStoryFromRelease",
    "updateRelease"
  ],
  "testcase-write": [
    "batchAssignTestCases",
    "batchChangeTestCaseBranch",
    "batchChangeTestCaseModule",
    "batchChangeTestCaseType",
    "batchConfirmTestCaseStoryChange",
    "batchCreateTestCases",
    "batchDeleteTestCases",
    "batchEditTestCases",
    "batchReviewTestCases",
    "confirmTestCaseChange",
    "confirmTestCaseLibcaseChange",
    "confirmTestCaseStoryChange",
    "createBugFromTestCase",
    "createTestCase",
    "deleteTestCase",
    "editTestCaseViaForm",
    "exportTestCases",
    "exportTestCaseTemplate",
    "ignoreTestCaseLibcaseChange",
    "importTestCases",
    "importTestCasesFromLib",
    "importTestCaseToLib",
    "linkBugToTestCase",
    "linkCasesToBug",
    "linkCasesToTestCase",
    "reviewTestCase",
    "unlinkBugFromTestCase",
    "updateTestCase"
  ],
  "testtask-write": [
    "activateTestTask",
    "batchAssignTestTasks",
    "batchRunTestCases",
    "batchUnlinkCases",
    "blockTestTask",
    "closeTestTask",
    "createTestTask",
    "deleteTestTask",
    "importTestTaskUnitResult",
    "linkCaseToTestTask",
    "runCase",
    "startTestTask",
    "unlinkCase",
    "updateTestTask"
  ],
  "product-write": [
    "addProductWhitelist",
    "batchEditProducts",
    "closeProduct",
    "createProduct",
    "deleteProduct",
    "editProduct",
    "exportProducts",
    "getProductAll",
    "getProductDashboard",
    "getProductDynamic",
    "getProductRoadmap",
    "getProductTrack",
    "getProductWhitelist",
    "setProductOrder",
    "unbindProductWhitelist"
  ],
  "project-write": [
    "activateProject",
    "addProjectWhitelist",
    "batchEditProjects",
    "closeProject",
    "copyProjectGroup",
    "createProject",
    "createProjectGroup",
    "deleteProject",
    "editProject",
    "editProjectGroup",
    "getProjectDynamic",
    "getProjectGroup",
    "getProjectLinkedProducts",
    "getProjectManageMembers",
    "getProjectTeam",
    "getProjectWhitelist",
    "setProjectOrder",
    "startProject",
    "suspendProject",
    "unbindProjectWhitelist",
    "unlinkProjectMember"
  ],
  "program-write": [
    "activateProgram",
    "batchUnlinkProgramStakeholders",
    "closeProgram",
    "createProgram",
    "createProgramStakeholder",
    "deleteProgram",
    "editProgram",
    "getProgramAll",
    "getProgramStakeholders",
    "getProgramTrack",
    "setProgramOrder",
    "startProgram",
    "suspendProgram",
    "unbindProgramWhitelist",
    "unlinkProgramStakeholder"
  ]
};
