import type { CliRegistry } from './cli-registry.js';
import type { Role } from '../types/common.js';
import { hasToolGroup } from './roles.js';
import { registerBugTools } from '../tools/bug.js';
import { registerBuildTools } from '../tools/build.js';
import { registerCommentTools } from '../tools/comment.js';
import { registerContextTools } from '../tools/context.js';
import { registerExecutionTools } from '../tools/execution.js';
import { registerInitTools } from '../tools/init.js';
import { registerProfileTools } from '../tools/profile.js';
import { registerProductTools } from '../tools/product.js';
import { registerProgramTools } from '../tools/program.js';
import { registerProjectTools } from '../tools/project.js';
import { registerPlanTools } from '../tools/plan.js';
import { registerPlanRelationTools, registerStoryWriteTools, registerTaskDerivedTools } from '../tools/phase3a.js';
import { registerBuildWriteTools, registerExecutionWriteTools, registerTestCaseWriteTools, registerTestTaskWriteTools } from '../tools/phase3b.js';
import { registerRelationTools } from '../tools/relation.js';
import { registerReleaseTools } from '../tools/release.js';
import { registerResourceAnalysisTools } from '../tools/resource-analysis.js';
import { registerStatisticsTools } from '../tools/statistics.js';
import { registerStoryTools } from '../tools/story.js';
import { registerTaskTools } from '../tools/task.js';
import { registerTestCaseTools } from '../tools/testcase.js';
import { registerTestTaskTools } from '../tools/testtask.js';
import { registerSearchTools } from '../tools/search.js';
import { registerTodoTools } from '../tools/todo.js';

export function registerTools(server: CliRegistry, role: Role): void {
  if (hasToolGroup(role, 'init')) registerInitTools(server);
  if (hasToolGroup(role, 'task')) registerTaskTools(server);
  if (hasToolGroup(role, 'todo')) registerTodoTools(server);
  if (hasToolGroup(role, 'bug')) registerBugTools(server);
  if (hasToolGroup(role, 'story')) registerStoryTools(server);
  if (hasToolGroup(role, 'execution')) registerExecutionTools(server);
  if (hasToolGroup(role, 'comment')) registerCommentTools(server);
  if (hasToolGroup(role, 'profile')) registerProfileTools(server);
  if (hasToolGroup(role, 'statistics')) registerStatisticsTools(server);
  if (hasToolGroup(role, 'relation')) registerRelationTools(server);
  if (hasToolGroup(role, 'context')) registerContextTools(server);
  if (hasToolGroup(role, 'product')) registerProductTools(server);
  if (hasToolGroup(role, 'project')) registerProjectTools(server);
  if (hasToolGroup(role, 'testcase')) registerTestCaseTools(server);
  if (hasToolGroup(role, 'testtask')) registerTestTaskTools(server);
  if (hasToolGroup(role, 'program')) registerProgramTools(server);
  if (hasToolGroup(role, 'plan')) registerPlanTools(server);
  if (hasToolGroup(role, 'build')) registerBuildTools(server);
  if (hasToolGroup(role, 'release')) registerReleaseTools(server);
  if (hasToolGroup(role, 'resource-analysis')) registerResourceAnalysisTools(server);
  if (hasToolGroup(role, 'search')) registerSearchTools(server);
  if (hasToolGroup(role, 'story-write')) registerStoryWriteTools(server);
  if (hasToolGroup(role, 'task-derived')) registerTaskDerivedTools(server);
  if (hasToolGroup(role, 'plan-relation')) registerPlanRelationTools(server);
  if (hasToolGroup(role, 'execution-write')) registerExecutionWriteTools(server);
  if (hasToolGroup(role, 'build-write')) registerBuildWriteTools(server);
  if (hasToolGroup(role, 'testcase-write')) registerTestCaseWriteTools(server);
  if (hasToolGroup(role, 'testtask-write')) registerTestTaskWriteTools(server);
}
